library(shinythemes)

fixedPage(theme = shinytheme("sandstone"),
  
  title = "Dynamic-RRT",
  div(style="text-align:center;", h4(style="font-weight: bold;", "Personalizing renal replacement therapy initiation in the ICU:")),
  div(style="text-align:center;", h4(style="font-weight: bold;", "a statistical reinforcement learning approach")),
  #textOutput("pol_rec_0"), textOutput("pol_rec_1"), textOutput("pol_rec_2"), textOutput("pol_rec_3"),
  br(),
  div(style="text-align:center;", "For a patient with stage 3 KDIGO-AKI and the evolving characteristics below, the stringent strategy recommends:" ),
  div(style="text-align:center; color:blue;", h5(textOutput("pol_rec_0")) ),
  div(style="text-align:center; color:red;", h5(textOutput("pol_rec_1")) ),
  div(style="text-align:center; color:red;", h5(textOutput("pol_rec_2")) ),
  div(style="text-align:center; color:red;", h5(textOutput("pol_rec_3")) ),
  
  plotOutput('plot', width = "1050px", height = "350px"), #plotOutput('plot', width = "auto", height = "350px"),
  hr(),
  
  fixedRow(
    column(4,
           h4("First day", align = "center"),
           p("Plug values the variables below take at the time stage 3 KDIGO-AKI occurs."),
           br(),
           numericInput("age", HTML('Age (years) <div style="font-size:10px; font-weight: normal;">range in validation set: 19 to 90</div>'),
                        value = 70, min = 18, max = 90, step = 1),
           numericInput("creat_k1", HTML('Creatinine (mg/dL) <div style="font-size:10px; font-weight: normal;">range in validation set: 0.3 to 10.4</div>'),
                        value = 2.5, min = 1, max = 12, step = .1),
           numericInput("bun_k1", HTML('Blood urea nitrogen (mg/dL) <div style="font-size:10px; font-weight: normal;">range in validation set: 5 to 140</div>'),
                        value = 55, min = 5, max = 200, step = 1),
           numericInput("pot_k1", HTML('Potassium (mmol/L) <div style="font-size:10px; font-weight: normal;">range in validation set: 2.6 to 8.0</div>'),
                        value = 5, min = 1.5, max = 10, step = .1),
           numericInput("ph_k1", HTML('pH (mmol/L) <div style="font-size:10px; font-weight: normal;">range in validation set: 6.88 to 7.63</div>'),
                        value = 7.3, min = 6.9, max = 7.6, step = .01),
           numericInput("uo_k1", HTML('Urine output (mL/kg/h) <div style="font-size:10px; font-weight: normal;">range in validation set: 0.0 to 7.2</div>'),
                        value = 0.1, min = 0, max = 8, step = .1)
    ),
    column(4, 
           h4("Second day", align = "center"),
           p("Plug values the variables below take just before stage 3 KDIGO-AKI occurrence + 24 hours.†"),
           br(),
           numericInput("sofa", HTML('SOFA <div style="font-size:10px; font-weight: normal;">range in validation set: 3 to 20</div>'),
                        value = 10, min = 0, max = 23, step = 1),
           numericInput("bun_k2", HTML('Blood urea nitrogen (mg/dL) <div style="font-size:10px; font-weight: normal;">range in validation set: 5 to 215</div>'),
                        value = 65, min = 5, max = 300, step = 1),
           numericInput("ph_k2", HTML('pH (mmol/L) <div style="font-size:10px; font-weight: normal;">range in validation set: 6.50 to 7.63</div>'),
                        value = 7.35, min = 6.9, max = 7.6, step = .01),
           numericInput("uo_k2", HTML('Urine output (mL/kg/h) <div style="font-size:10px; font-weight: normal;">range in validation set: 0.0 to 4.8</div>'),
                        value = 0, min = 0, max = 8, step = .1)
    ),
    column(4,
           h4("Third day", align = "center"),
           p("Plug values the variables below take just before stage 3 KDIGO-AKI occurrence + 48 hours.‡"),
           br(),
           numericInput("bun_k3", HTML('Blood urea nitrogen (mg/dL) <div style="font-size:10px; font-weight: normal;">range in validation set: 5 to 151</div>'),
                        value = 68, min = 5, max = 300, step = 1),
           numericInput("uo_k3", HTML('Urine output (mL/kg/h) <div style="font-size:10px; font-weight: normal;">range in validation set: 0.0 to 4.5</div>'),
                        value = 0, min = 0, max = 8, step = .1),
           br(),
           div(style="display:inline-block; margin-left:5px", submitButton("See individual-patient recommendation")),
           br(),br(),
           p("Show blips for patients from", align = "left"),
           checkboxInput('mimic', 'MIMIC-III (development set)', value = TRUE),
           checkboxInput('akiki', 'AKIKI trials (validation set)', value = TRUE)
    )
  ),
  p(style="font-size:11px; line-height:12px; margin: 10px;", '† Note that pH and urine output at the time stage 3 KDIGO-AKI occurs also affect day 2 recomendation.'),
  p(style="font-size:11px; line-height:12px; margin: 10px;", '‡ Note that blood urea nitrogen at the time stage 3 KDIGO-AKI occurs also affect day 3 recomendation.'),
  p(style="font-size:11px; line-height:12px; margin: 10px;", 'Intervals for the blips are 95% confidence intervals. Dots falling in grey-shaded aeras represent patients for whom there is evidence of either harm (left-hand aeras), or benefit (right-hand aeras) from RRT initiation at the .05 alpha level. AKI = Acute Kidney Injury; HFD = Hospital-Free Days; KDIGO = Kidney Disease: Improving Global Outcomes; RRT = Renal-Replacement Therapy.'),
  br(),
  h3("References"),
  p("Grolleau F et al. Personalising renal replacement therapy initiation in the intensive care unit: a statistical reinforcement learning-based dynamic strategy with external validation on the AKIKI randomised controlled trials. (medRxiv, TBA)."),
  p("Gaudry S et al. Extracorporeal kidney-replacement therapy for acute kidney injury. N Engl J Med 2022; 386: 964–75."),
  br(),
  tags$a(href="http://cress-umr1153.fr/", 
         img(src='cress.png', align = "right", style="width:149px;height:57px;")),
  tags$a(href="https://u-paris.fr/", 
  img(src='uparis.png', align = "right", style="width:146px;height:57px;")),
  HTML('Contact: François Grolleau; francois.grolleau [ a t ] aphp.fr <BR> 
       This is a research tool and is not intended for clinical use. <BR>
       © Dynamic-RRT 2022. All Rights Reserved.')
)